package io.fluentjava.maven;

import org.apache.maven.plugin.AbstractMojo;
import org.apache.maven.plugin.MojoExecutionException;
import org.apache.maven.plugins.annotations.LifecyclePhase;
import org.apache.maven.plugins.annotations.Mojo;
import org.apache.maven.plugins.annotations.Parameter;
import org.apache.maven.project.MavenProject;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.stream.Stream;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Scans project sources for {@code @FluentExtension} annotated classes and
 * generates the {@code META-INF/fluentjava/extensions} resource file that
 * the javac plugin reads at compile time.
 *
 * <p>Compiler configuration (dependency, fork, --add-exports) is handled by
 * {@link FluentJavaLifecycleParticipant} which runs before lifecycle
 * computation when the plugin is declared with {@code <extensions>true</extensions>}.</p>
 *
 * @since 1.0.0
 */
@Mojo(name = "configure", defaultPhase = LifecyclePhase.INITIALIZE)
public class FluentJavaMojo extends AbstractMojo {

    private static final Pattern PACKAGE_PATTERN = Pattern.compile("(?m)^\\s*package\\s+([\\w.]+)\\s*;");
    private static final Pattern TYPE_PATTERN = Pattern.compile("(?m)^\\s*(?:public\\s+)?(?:final\\s+|abstract\\s+)?(?:class|record|interface|enum)\\s+([A-Za-z_][A-Za-z0-9_]*)\\b");
    private static final Pattern EXTENSION_PATTERN = Pattern.compile("@(?:[\\w.]+\\.)?FluentExtension\\s*\\(\\s*target\\s*=\\s*([\\w.$]+)\\s*\\.class\\s*\\)");

    @Parameter(defaultValue = "${project}", readonly = true, required = true)
    private MavenProject project;

    @Override
    public void execute() throws MojoExecutionException {
        generateExtensionsResource();
        getLog().info("[FluentJava] Done \u2014 FluentJava is ready.");
    }

    // ── Extensions resource generation ────────────────────────────────

    private void generateExtensionsResource() throws MojoExecutionException {
        Set<String> extensionClasses = new LinkedHashSet<>();

        for (String sourceRoot : project.getCompileSourceRoots()) {
            Path root = Paths.get(sourceRoot);
            if (!Files.isDirectory(root)) {
                continue;
            }
            scanSourceRootForExtensions(root, extensionClasses);
        }

        Path output = Paths.get(project.getBuild().getOutputDirectory())
                .resolve("META-INF")
                .resolve("fluentjava")
                .resolve("extensions");
        try {
            Files.createDirectories(output.getParent());
            List<String> lines = new ArrayList<>();
            lines.add("# Auto-generated by fluentjava-maven-plugin");
            lines.add("# Classes annotated with @FluentExtension");
            lines.addAll(extensionClasses);
            Files.write(output, lines, StandardCharsets.UTF_8);
            getLog().info("FluentJava: generated " + output + " with " + extensionClasses.size() + " extension class(es)");
        } catch (IOException e) {
            throw new MojoExecutionException("Failed to generate META-INF/fluentjava/extensions", e);
        }
    }

    private void scanSourceRootForExtensions(Path root, Set<String> extensionClasses) throws MojoExecutionException {
        try (Stream<Path> stream = Files.walk(root)) {
            stream
                    .filter(p -> p.toString().endsWith(".java"))
                    .forEach(javaFile -> scanJavaFile(javaFile, extensionClasses));
        } catch (IOException e) {
            throw new MojoExecutionException("Failed to scan sources for @FluentExtension in " + root, e);
        }
    }

    private void scanJavaFile(Path javaFile, Set<String> extensionClasses) {
        String source;
        try {
            source = Files.readString(javaFile, StandardCharsets.UTF_8);
        } catch (IOException e) {
            getLog().warn("FluentJava: unable to read " + javaFile + " (" + e.getMessage() + ")");
            return;
        }

        Matcher extMatcher = EXTENSION_PATTERN.matcher(source);
        if (!extMatcher.find()) {
            return;
        }

        String pkg = "";
        Matcher packageMatcher = PACKAGE_PATTERN.matcher(source);
        if (packageMatcher.find()) {
            pkg = packageMatcher.group(1);
        }

        Matcher typeMatcher = TYPE_PATTERN.matcher(source);
        if (!typeMatcher.find()) {
            getLog().warn("FluentJava: @FluentExtension found but no top-level type in " + javaFile);
            return;
        }

        String simpleName = typeMatcher.group(1);
        String fqn = pkg.isEmpty() ? simpleName : pkg + "." + simpleName;
        extensionClasses.add(fqn);
    }
}
